# 选择基础镜像
FROM node:14 as builder

# 设置镜像源为淘宝
#RUN npm config set registry https://registry.npm.taobao.org \
#    && npm config set disturl https://npm.taobao.org/dist 

# 进入前后端工作目录安装依赖包
WORKDIR /app/frontend
COPY ./explorer_admin/frontend/package.json .
RUN npm install 

WORKDIR /app/backend
COPY ./explorer_admin/backend/package.json .
RUN npm install 
COPY ./explorer_admin/backend .

# 进入前端工作目录编译静态文件
WORKDIR /app/frontend
COPY ./explorer_admin/frontend .
RUN npm run build

######################## 二次构建
FROM node:14

# 设置镜像源为淘宝
#RUN npm config set registry https://registry.npm.taobao.org \
#    && npm config set disturl https://npm.taobao.org/dist \ 
#    && npm install pm2 -g
RUN npm install pm2 -g

# 进入后端工作目录
WORKDIR /app/backend
# 复制后端代码
COPY --from=builder /app/backend .

# 修改时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

EXPOSE 3000

# 启动服务
# CMD pm2-runtime /app/backend/pm2.json
# docker build -f Dockerfile_build -t zg_admin:latest .