# 选择编译镜像
FROM python:3.7

WORKDIR /www
COPY explorer_s_explorer_v2/requirements.txt .

RUN pip install -i https://pypi.doubanio.com/simple/ -r requirements.txt

# 修改时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 编译基础包
# docker build -f Dockerfile_python_explorer -t explorer_python_explorer:dev .
