# 基础镜像
FROM node:12

# 设置镜像源为淘宝
#RUN npm config set registry https://registry.npm.taobao.org \
#    && npm config set disturl https://npm.taobao.org/dist \ 
#    && npm install pm2 -g
RUN npm install pm2 -g

# 进入后端工作目录
WORKDIR /app

# 复制包文件
COPY ./explorer_web/package.json .

# 安装依赖包
RUN npm install

# 复制代码
COPY ./explorer_web/ .

# 编译
RUN npm run build

# 修改时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

EXPOSE 3000

# 启动服务
# CMD pm2-runtime /app/backend/pm2.json
# docker build -f Dockerfile_build -t zg_admin:latest .